kind: filecop
name: Filecop
description: "Detects potentially hazardeous commited files and strings such as private keys, passwords, access tokens and certs"
discovers: sensitive file
author: 
  name: Tom Moor
  email: tom.moor@gmail.com
repository:
  type: git
  url: https://github.com/pushbit-behaviors/filecop
tone: negative
active: true
triggers:
  - pull_request_opened
actions:
  - line_comment
keywords:
  - token
  - password
  - key